import { Projects } from './types'
export const projects: Projects[] = [
    {
        category: 'Music',
        color: '#03dac6',
        projects: [
            {
                id: 1,
                name: 'Project A',
                description: 'Description A',
                location: 'Reykjavík',
                date: 'Sunday Sept 20, 2020',
            },
            {
                id: 2,
                name: 'Project B',
                description: 'Description B',
                location: 'Reykjavík',
                date: 'Sunday Sept 20, 2020',
            },
            {
                id: 3,
                name: 'Project C',
                description: 'Description C',
                location: 'Reykjavík',
                date: 'Sunday Sept 20, 2020',
            },
            {
                id: 4,
                name: 'Project D',
                description: 'Description D',
                location: 'Reykjavík',
                date: 'Sunday Sept 20, 2020',
            },
            {
                id: 5,
                name: 'Project E',
                description: 'Description E',
                location: 'Reykjavík',
                date: 'Sunday Sept 20, 2020',
            },
        ],
    },
    {
        category: 'Movies',
        color: '#00B0FF',
        projects: [
            {
                id: 6,
                name: 'Project A',
                description: 'Description A',
                location: 'Reykjavík',
                date: 'Sunday Sept 20, 2020',
            },
            {
                id: 7,
                name: 'Project B',
                description: 'Description B',
                location: 'Reykjavík',
                date: 'Sunday Sept 20, 2020',
            },
            {
                id: 8,
                name: 'Project C',
                description: 'Description C',
                location: 'Reykjavík',
                date: 'Sunday Sept 20, 2020',
            },
            {
                id: 9,
                name: 'Project D',
                description: 'Description D',
                location: 'Reykjavík',
                date: 'Sunday Sept 20, 2020',
            },
            {
                id: 10,
                name: 'Project E',
                description: 'Description E',
                location: 'Reykjavík',
                date: 'Sunday Sept 20, 2020',
            },
        ],
    },
    {
        category: 'Art',
        color: '#FFA000',
        projects: [
            {
                id: 11,
                name: 'Project A',
                description: 'Description A',
                location: 'Reykjavík',
                date: 'Sunday Sept 20, 2020',
            },
            {
                id: 12,
                name: 'Project B',
                description: 'Description B',
                location: 'Reykjavík',
                date: 'Sunday Sept 20, 2020',
            },
            {
                id: 13,
                name: 'Project C',
                description: 'Description C',
                location: 'Reykjavík',
                date: 'Sunday Sept 20, 2020',
            },
            {
                id: 14,
                name: 'Project D',
                description: 'Description D',
                location: 'Reykjavík',
                date: 'Sunday Sept 20, 2020',
            },
            {
                id: 15,
                name: 'Project E',
                description: 'Description E',
                location: 'Reykjavík',
                date: 'Sunday Sept 20, 2020',
            },
        ],
    },
    {
        category: 'Dance',
        color: '#AA00FF',
        projects: [
            {
                id: 16,
                name: 'Project A',
                description: 'Description A',
                location: 'Reykjavík',
                date: 'Sunday Sept 20, 2020',
            },
            {
                id: 17,
                name: 'Project B',
                description: 'Description B',
                location: 'Reykjavík',
                date: 'Sunday Sept 20, 2020',
            },
            {
                id: 18,
                name: 'Project C',
                description: 'Description C',
                location: 'Reykjavík',
                date: 'Sunday Sept 20, 2020',
            },
            {
                id: 19,
                name: 'Project D',
                description: 'Description D',
                location: 'Reykjavík',
                date: 'Sunday Sept 20, 2020',
            },
            {
                id: 20,
                name: 'Project E',
                description: 'Description E',
                location: 'Reykjavík',
                date: 'Sunday Sept 20, 2020',
            },
        ],
    },
]
